name: consonant_cooccurrence
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.2
  - r-viridis
  - r-extrafont
  - r-ape
  - r-cairo
  - r-corrplot
  - r-tidyverse
  - r-knitr
  - r-rmarkdown
